// recipespire-frontend/src/pages/Ingredients/IngredientList.jsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Search, Edit, Trash2, Package } from 'lucide-react';
import { ingredientService } from '../../services/ingredientService';
import LoadingSpinner from '../../components/UI/LoadingSpinner';
import ConfirmDialog from '../../components/UI/ConfirmDialog';
import { useToast } from '../../hooks/useToast';

const IngredientList = () => {
  const [ingredients, setIngredients] = useState([]);
  const [filteredIngredients, setFilteredIngredients] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('');
  const [categories, setCategories] = useState([]);
  const [deleteDialog, setDeleteDialog] = useState({ isOpen: false, ingredientId: null });
  
  const { showSuccess, showError } = useToast();

  useEffect(() => {
    loadIngredients();
  }, []);

  useEffect(() => {
    filterIngredients();
  }, [ingredients, searchQuery, selectedCategory]);

  const loadIngredients = async () => {
    try {
      setLoading(true);
      const response = await ingredientService.getAllIngredients();
      setIngredients(response.data);
      extractCategories(response.data);
    } catch (error) {
      console.error('Error loading ingredients:', error);
      showError('Error', 'Failed to load ingredients');
    } finally {
      setLoading(false);
    }
  };

  const extractCategories = (ingredientsList) => {
    const categorySet = new Set(
      ingredientsList.map(ing => ing.category).filter(cat => cat)
    );
    setCategories(Array.from(categorySet).sort());
  };

  const filterIngredients = () => {
    let filtered = ingredients;

    if (searchQuery.trim()) {
      filtered = filtered.filter(ingredient =>
        ingredient.name.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }

    if (selectedCategory) {
      filtered = filtered.filter(ingredient => ingredient.category === selectedCategory);
    }

    setFilteredIngredients(filtered);
  };

  const handleDeleteIngredient = async () => {
    try {
      await ingredientService.deleteIngredient(deleteDialog.ingredientId);
      showSuccess('Success', 'Ingredient deleted successfully');
      loadIngredients();
    } catch (error) {
      console.error('Error deleting ingredient:', error);
      showError('Error', 'Failed to delete ingredient');
    } finally {
      setDeleteDialog({ isOpen: false, ingredientId: null });
    }
  };

  if (loading) {
    return <LoadingSpinner />;
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Ingredients</h1>
          <p className="mt-2 text-gray-600">Manage your ingredient database</p>
        </div>
        <Link
          to="/ingredients/new"
          className="mt-4 sm:mt-0 btn-primary inline-flex items-center"
        >
          <Plus className="w-5 h-5 mr-2" />
          Add Ingredient
        </Link>
      </div>

      {/* Search and Filter */}
      <div className="card">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="form-label">Search Ingredients</label>
            <div className="relative">
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search by name..."
                className="form-input pl-10"
              />
              <Search className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
            </div>
          </div>
          <div>
            <label className="form-label">Filter by Category</label>
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="form-input"
            >
              <option value="">All Categories</option>
              {categories.map((category) => (
                <option key={category} value={category}>
                  {category}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Ingredients Table */}
      {filteredIngredients.length > 0 ? (
        <div className="card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Name
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Category
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Unit
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Calories/Unit
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredIngredients.map((ingredient) => (
                  <tr key={ingredient.id} className="hover:bg-gray-50 transition-colors duration-200">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-gray-900">{ingredient.name}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                        {ingredient.category || 'Uncategorized'}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {ingredient.unit}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {ingredient.caloriesPerUnit || 'N/A'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-2">
                      <Link
                        to={`/ingredients/${ingredient.id}/edit`}
                        className="text-primary-600 hover:text-primary-700 transition-colors duration-200 inline-flex items-center"
                      >
                        <Edit className="w-4 h-4 mr-1" />
                        Edit
                      </Link>
                      <button
                        onClick={() => setDeleteDialog({ isOpen: true, ingredientId: ingredient.id })}
                        className="text-red-600 hover:text-red-700 transition-colors duration-200 inline-flex items-center"
                      >
                        <Trash2 className="w-4 h-4 mr-1" />
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        <div className="text-center py-12">
          <Package className="mx-auto h-12 w-12 text-gray-400 mb-4" />
          <h3 className="mt-2 text-sm font-medium text-gray-900">No ingredients found</h3>
          <p className="mt-1 text-sm text-gray-500">Get started by adding your first ingredient.</p>
          <div className="mt-6">
            <Link to="/ingredients/new" className="btn-primary">
              <Plus className="w-5 h-5 mr-2" />
              Add Ingredient
            </Link>
          </div>
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={deleteDialog.isOpen}
        onClose={() => setDeleteDialog({ isOpen: false, ingredientId: null })}
        onConfirm={handleDeleteIngredient}
        title="Delete Ingredient"
        message="Are you sure you want to delete this ingredient? This action cannot be undone."
        confirmText="Delete"
        cancelText="Cancel"
      />
    </div>
  );
};

export default IngredientList;

// recipe-spire/src/app/features/ingredients/ingredient-list/ingredient-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Ingredient } from '../../../shared/models/ingredient.model';
import { IngredientService } from '../../../core/services/ingredient.service';
import { ToastService } from '../../../shared/services/toast.service';

@Component({
  selector: 'app-ingredient-list',
  templateUrl: './ingredient-list.component.html',
  styleUrls: ['./ingredient-list.component.css']
})
export class IngredientListComponent implements OnInit {
  ingredients: Ingredient[] = [];
  filteredIngredients: Ingredient[] = [];
  searchQuery = '';
  selectedCategory = '';
  categories: string[] = [];
  loading = false;
  showConfirmDialog = false;
  ingredientToDelete?: number;

  constructor(
    private ingredientService: IngredientService,
    private router: Router,
    private toastService: ToastService
  ) {}

  ngOnInit() {
    this.loadIngredients();
  }

  loadIngredients() {
    this.loading = true;
    this.ingredientService.getAllIngredients().subscribe({
      next: (ingredients) => {
        this.ingredients = ingredients;
        this.filteredIngredients = ingredients;
        this.extractCategories();
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading ingredients:', error);
        this.toastService.showError('Error', 'Failed to load ingredients');
        this.loading = false;
      }
    });
  }

  extractCategories() {
    const categorySet = new Set(this.ingredients.map(ing => ing.category).filter(cat => cat));
    this.categories = Array.from(categorySet).sort();
  }

  onSearch() {
    this.filterIngredients();
  }

  onCategoryFilter() {
    this.filterIngredients();
  }

  filterIngredients() {
    let filtered = this.ingredients;

    if (this.searchQuery.trim()) {
      filtered = filtered.filter(ingredient =>
        ingredient.name.toLowerCase().includes(this.searchQuery.toLowerCase())
      );
    }

    if (this.selectedCategory) {
      filtered = filtered.filter(ingredient => ingredient.category === this.selectedCategory);
    }

    this.filteredIngredients = filtered;
  }

  editIngredient(id: number) {
    this.router.navigate(['/ingredients', id, 'edit']);
  }

  confirmDeleteIngredient(id: number) {
    this.ingredientToDelete = id;
    this.showConfirmDialog = true;
  }

  deleteIngredient() {
    if (this.ingredientToDelete) {
      this.ingredientService.deleteIngredient(this.ingredientToDelete).subscribe({
        next: () => {
          this.toastService.showSuccess('Success', 'Ingredient deleted successfully');
          this.loadIngredients();
          this.showConfirmDialog = false;
          this.ingredientToDelete = undefined;
        },
        error: (error) => {
          console.error('Error deleting ingredient:', error);
          this.toastService.showError('Error', 'Failed to delete ingredient');
          this.showConfirmDialog = false;
        }
      });
    }
  }

  cancelDelete() {
    this.showConfirmDialog = false;
    this.ingredientToDelete = undefined;
  }
}
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <!-- Header -->
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8">
    <div>
      <h1 class="text-3xl font-bold text-gray-900">Ingredients</h1>
      <p class="mt-2 text-gray-600">Manage your ingredient database</p>
    </div>
    <button routerLink="/ingredients/new" 
            class="mt-4 sm:mt-0 btn-primary inline-flex items-center">
      <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
      </svg>
      Add Ingredient
    </button>
  </div>

  <!-- Search and Filter -->
  <div class="card mb-8">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        <label class="form-label">Search Ingredients</label>
        <div class="relative">
          <input type="text" 
                 [(ngModel)]="searchQuery"
                 (input)="onSearch()"
                 placeholder="Search by name..."
                 class="form-input pl-10">
          <svg class="absolute left-3 top-3 h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
          </svg>
        </div>
      </div>
      <div>
        <label class="form-label">Filter by Category</label>
        <select [(ngModel)]="selectedCategory" 
                (change)="onCategoryFilter()"
                class="form-input">
          <option value="">All Categories</option>
          <option *ngFor="let category of categories" [value]="category">{{category}}</option>
        </select>
      </div>
    </div>
  </div>

  <!-- Loading State -->
  <app-loading-spinner *ngIf="loading"></app-loading-spinner>

  <!-- Ingredients Table -->
  <div *ngIf="!loading" class="card overflow-hidden">
    <div class="overflow-x-auto">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Category</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Unit</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Calories/Unit</th>
            <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr *ngFor="let ingredient of filteredIngredients" class="hover:bg-gray-50 transition-colors duration-200">
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm font-medium text-gray-900">{{ingredient.name}}</div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                {{ingredient.category || 'Uncategorized'}}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              {{ingredient.unit}}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              {{ingredient.caloriesPerUnit || 'N/A'}}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-2">
              <button (click)="editIngredient(ingredient.id!)" 
                      class="text-primary-600 hover:text-primary-700 transition-colors duration-200">
                Edit
              </button>
              <button (click)="confirmDeleteIngredient(ingredient.id!)" 
                      class="text-red-600 hover:text-red-700 transition-colors duration-200">
                Delete
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Empty State -->
    <div *ngIf="filteredIngredients.length === 0" class="text-center py-12">
      <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path>
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900">No ingredients found</h3>
      <p class="mt-1 text-sm text-gray-500">Get started by adding your first ingredient.</p>
      <div class="mt-6">
        <button routerLink="/ingredients/new" class="btn-primary">
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
          </svg>
          Add Ingredient
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Confirm Delete Dialog -->
<app-confirm-dialog
  [isOpen]="showConfirmDialog"
  title="Delete Ingredient"
  message="Are you sure you want to delete this ingredient? This action cannot be undone."
  confirmText="Delete"
  cancelText="Cancel"
  (confirmed)="deleteIngredient()"
  (cancelled)="cancelDelete()">
</app-confirm-dialog>
