// recipespire-frontend/src/pages/Inventory/InventoryList.jsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Search, Edit, Trash2, Package } from 'lucide-react';
import { inventoryService } from '../../services/inventoryService';
import LoadingSpinner from '../../components/UI/LoadingSpinner';
import ConfirmDialog from '../../components/UI/ConfirmDialog';
import { useToast } from '../../hooks/useToast';

const InventoryList = () => {
  const [inventoryItems, setInventoryItems] = useState([]);
  const [filteredItems, setFilteredItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedStatus, setSelectedStatus] = useState('');
  const [deleteDialog, setDeleteDialog] = useState({ isOpen: false, itemId: null });
  
  const { showSuccess, showError } = useToast();

  const statusOptions = [
    { value: 'IN_STOCK', label: 'In Stock', color: 'bg-green-100 text-green-800' },
    { value: 'LOW_STOCK', label: 'Low Stock', color: 'bg-yellow-100 text-yellow-800' },
    { value: 'OUT_OF_STOCK', label: 'Out of Stock', color: 'bg-red-100 text-red-800' },
  ];

  useEffect(() => {
    loadInventoryItems();
  }, []);

  useEffect(() => {
    filterItems();
  }, [inventoryItems, searchQuery, selectedStatus]);

  const loadInventoryItems = async () => {
    try {
      setLoading(true);
      const response = await inventoryService.getAllInventoryItems();
      setInventoryItems(response.data);
    } catch (error) {
      console.error('Error loading inventory items:', error);
      showError('Error', 'Failed to load inventory items');
    } finally {
      setLoading(false);
    }
  };

  const filterItems = () => {
    let filtered = inventoryItems;

    if (searchQuery.trim()) {
      filtered = filtered.filter(item =>
        item.ingredient.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (item.location && item.location.toLowerCase().includes(searchQuery.toLowerCase()))
      );
    }

    if (selectedStatus) {
      filtered = filtered.filter(item => item.status === selectedStatus);
    }

    setFilteredItems(filtered);
  };

  const handleDeleteItem = async () => {
    try {
      await inventoryService.removeFromInventory(deleteDialog.itemId);
      showSuccess('Success', 'Item removed from inventory');
      loadInventoryItems();
    } catch (error) {
      console.error('Error deleting inventory item:', error);
      showError('Error', 'Failed to remove item');
    } finally {
      setDeleteDialog({ isOpen: false, itemId: null });
    }
  };

  const getStatusColor = (status) => {
    const statusOption = statusOptions.find(option => option.value === status);
    return statusOption?.color || 'bg-gray-100 text-gray-800';
  };

  const getStatusLabel = (status) => {
    const statusOption = statusOptions.find(option => option.value === status);
    return statusOption?.label || status;
  };

  const isExpiringSoon = (item) => {
    if (!item.expirationDate) return false;
    const today = new Date();
    const expiration = new Date(item.expirationDate);
    const daysUntilExpiration = Math.ceil((expiration.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
    return daysUntilExpiration <= 7 && daysUntilExpiration >= 0;
  };

  const isExpired = (item) => {
    if (!item.expirationDate) return false;
    const today = new Date();
    const expiration = new Date(item.expirationDate);
    return expiration < today;
  };

  if (loading) {
    return <LoadingSpinner />;
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Inventory</h1>
          <p className="mt-2 text-gray-600">Track your ingredient stock levels</p>
        </div>
        <Link
          to="/inventory/new"
          className="mt-4 sm:mt-0 btn-primary inline-flex items-center"
        >
          <Plus className="w-5 h-5 mr-2" />
          Add to Inventory
        </Link>
      </div>

      {/* Search and Filter */}
      <div className="card">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="form-label">Search Inventory</label>
            <div className="relative">
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search by ingredient or location..."
                className="form-input pl-10"
              />
              <Search className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
            </div>
          </div>
          <div>
            <label className="form-label">Filter by Status</label>
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="form-input"
            >
              <option value="">All Status</option>
              {statusOptions.map((status) => (
                <option key={status.value} value={status.value}>
                  {status.label}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Inventory Table */}
      {filteredItems.length > 0 ? (
        <div className="card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Ingredient
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Quantity
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Location
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Expiration
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredItems.map((item) => (
                  <tr
                    key={item.id}
                    className={`hover:bg-gray-50 transition-colors duration-200 ${
                      isExpired(item) ? 'bg-red-50' : isExpiringSoon(item) ? 'bg-yellow-50' : ''
                    }`}
                  >
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-gray-900">{item.ingredient.name}</div>
                      <div className="text-sm text-gray-500">{item.ingredient.unit}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-gray-900">{item.quantity}</div>
                      {item.minStockLevel && (
                        <div className="text-xs text-gray-500">Min: {item.minStockLevel}</div>
                      )}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {item.location || 'Not specified'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(item.status)}`}>
                        {getStatusLabel(item.status)}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {item.expirationDate ? (
                        <div>
                          {new Date(item.expirationDate).toLocaleDateString()}
                          {isExpired(item) && (
                            <div className="text-xs text-red-600 font-medium">Expired</div>
                          )}
                          {isExpiringSoon(item) && !isExpired(item) && (
                            <div className="text-xs text-yellow-600 font-medium">Expires soon</div>
                          )}
                        </div>
                      ) : (
                        <span className="text-gray-400">No expiration</span>
                      )}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-2">
                      <Link
                        to={`/inventory/${item.id}/edit`}
                        className="text-primary-600 hover:text-primary-700 transition-colors duration-200 inline-flex items-center"
                      >
                        <Edit className="w-4 h-4 mr-1" />
                        Edit
                      </Link>
                      <button
                        onClick={() => setDeleteDialog({ isOpen: true, itemId: item.id })}
                        className="text-red-600 hover:text-red-700 transition-colors duration-200 inline-flex items-center"
                      >
                        <Trash2 className="w-4 h-4 mr-1" />
                        Remove
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        <div className="text-center py-12">
          <Package className="mx-auto h-12 w-12 text-gray-400 mb-4" />
          <h3 className="mt-2 text-sm font-medium text-gray-900">No inventory items found</h3>
          <p className="mt-1 text-sm text-gray-500">Start tracking your ingredients by adding them to inventory.</p>
          <div className="mt-6">
            <Link to="/inventory/new" className="btn-primary">
              <Plus className="w-5 h-5 mr-2" />
              Add to Inventory
            </Link>
          </div>
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={deleteDialog.isOpen}
        onClose={() => setDeleteDialog({ isOpen: false, itemId: null })}
        onConfirm={handleDeleteItem}
        title="Remove from Inventory"
        message="Are you sure you want to remove this item from inventory? This action cannot be undone."
        confirmText="Remove"
        cancelText="Cancel"
      />
    </div>
  );
};

export default InventoryList;

// recipe-spire/src/app/features/inventory/inventory-list/inventory-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { InventoryItem, InventoryStatus } from '../../../shared/models/inventory.model';
import { InventoryService } from '../../../core/services/inventory.service';
import { ToastService } from '../../../shared/services/toast.service';

@Component({
  selector: 'app-inventory-list',
  templateUrl: './inventory-list.component.html',
  styleUrls: ['./inventory-list.component.css']
})
export class InventoryListComponent implements OnInit {
  inventoryItems: InventoryItem[] = [];
  filteredItems: InventoryItem[] = [];
  searchQuery = '';
  selectedStatus = '';
  loading = false;
  showConfirmDialog = false;
  itemToDelete?: number;
  
  statusOptions = [
    { value: InventoryStatus.IN_STOCK, label: 'In Stock', color: 'bg-green-100 text-green-800' },
    { value: InventoryStatus.LOW_STOCK, label: 'Low Stock', color: 'bg-yellow-100 text-yellow-800' },
    { value: InventoryStatus.OUT_OF_STOCK, label: 'Out of Stock', color: 'bg-red-100 text-red-800' }
  ];

  constructor(
    private inventoryService: InventoryService,
    private router: Router,
    private toastService: ToastService
  ) {}

  ngOnInit() {
    this.loadInventoryItems();
  }

  loadInventoryItems() {
    this.loading = true;
    this.inventoryService.getAllInventoryItems().subscribe({
      next: (items) => {
        this.inventoryItems = items;
        this.filteredItems = items;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading inventory items:', error);
        this.toastService.showError('Error', 'Failed to load inventory items');
        this.loading = false;
      }
    });
  }

  onSearch() {
    this.filterItems();
  }

  onStatusFilter() {
    this.filterItems();
  }

  filterItems() {
    let filtered = this.inventoryItems;

    if (this.searchQuery.trim()) {
      filtered = filtered.filter(item =>
        item.ingredient.name.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
        (item.location && item.location.toLowerCase().includes(this.searchQuery.toLowerCase()))
      );
    }

    if (this.selectedStatus) {
      filtered = filtered.filter(item => item.status === this.selectedStatus);
    }

    this.filteredItems = filtered;
  }

  getStatusColor(status: InventoryStatus): string {
    const statusOption = this.statusOptions.find(option => option.value === status);
    return statusOption?.color || 'bg-gray-100 text-gray-800';
  }

  getStatusLabel(status: InventoryStatus): string {
    const statusOption = this.statusOptions.find(option => option.value === status);
    return statusOption?.label || status;
  }

  editInventoryItem(id: number) {
    this.router.navigate(['/inventory', id, 'edit']);
  }

  confirmDeleteInventoryItem(id: number) {
    this.itemToDelete = id;
    this.showConfirmDialog = true;
  }

  deleteInventoryItem() {
    if (this.itemToDelete) {
      this.inventoryService.removeFromInventory(this.itemToDelete).subscribe({
        next: () => {
          this.toastService.showSuccess('Success', 'Item removed from inventory');
          this.loadInventoryItems();
          this.showConfirmDialog = false;
          this.itemToDelete = undefined;
        },
        error: (error) => {
          console.error('Error deleting inventory item:', error);
          this.toastService.showError('Error', 'Failed to remove item');
          this.showConfirmDialog = false;
        }
      });
    }
  }

  cancelDelete() {
    this.showConfirmDialog = false;
    this.itemToDelete = undefined;
  }

  isExpiringSoon(item: InventoryItem): boolean {
    if (!item.expirationDate) return false;
    const today = new Date();
    const expiration = new Date(item.expirationDate);
    const daysUntilExpiration = Math.ceil((expiration.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
    return daysUntilExpiration <= 7 && daysUntilExpiration >= 0;
  }

  isExpired(item: InventoryItem): boolean {
    if (!item.expirationDate) return false;
    const today = new Date();
    const expiration = new Date(item.expirationDate);
    return expiration < today;
  }
}
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <!-- Header -->
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8">
    <div>
      <h1 class="text-3xl font-bold text-gray-900">Inventory</h1>
      <p class="mt-2 text-gray-600">Track your ingredient stock levels</p>
    </div>
    <button routerLink="/inventory/new" 
            class="mt-4 sm:mt-0 btn-primary inline-flex items-center">
      <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
      </svg>
      Add to Inventory
    </button>
  </div>

  <!-- Search and Filter -->
  <div class="card mb-8">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        <label class="form-label">Search Inventory</label>
        <div class="relative">
          <input type="text" 
                 [(ngModel)]="searchQuery"
                 (input)="onSearch()"
                 placeholder="Search by ingredient or location..."
                 class="form-input pl-10">
          <svg class="absolute left-3 top-3 h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
          </svg>
        </div>
      </div>
      <div>
        <label class="form-label">Filter by Status</label>
        <select [(ngModel)]="selectedStatus" 
                (change)="onStatusFilter()"
                class="form-input">
          <option value="">All Status</option>
          <option *ngFor="let status of statusOptions" [value]="status.value">{{status.label}}</option>
        </select>
      </div>
    </div>
  </div>

  <!-- Loading State -->
  <app-loading-spinner *ngIf="loading"></app-loading-spinner>

  <!-- Inventory Table -->
  <div *ngIf="!loading" class="card overflow-hidden">
    <div class="overflow-x-auto">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Ingredient</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Quantity</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Location</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Expiration</th>
            <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr *ngFor="let item of filteredItems" 
              class="hover:bg-gray-50 transition-colors duration-200"
              [class.bg-red-50]="isExpired(item)"
              [class.bg-yellow-50]="isExpiringSoon(item)">
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm font-medium text-gray-900">{{item.ingredient.name}}</div>
              <div class="text-sm text-gray-500">{{item.ingredient.unit}}</div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="text-sm text-gray-900">{{item.quantity}}</div>
              <div *ngIf="item.minStockLevel" class="text-xs text-gray-500">
                Min: {{item.minStockLevel}}
              </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              {{item.location || 'Not specified'}}
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
                    [class]="getStatusColor(item.status)">
                {{getStatusLabel(item.status)}}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              <div *ngIf="item.expirationDate">
                {{item.expirationDate | date:'shortDate'}}
                <div *ngIf="isExpired(item)" class="text-xs text-red-600 font-medium">Expired</div>
                <div *ngIf="isExpiringSoon(item) && !isExpired(item)" class="text-xs text-yellow-600 font-medium">
                  Expires soon
                </div>
              </div>
              <span *ngIf="!item.expirationDate" class="text-gray-400">No expiration</span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-2">
              <button (click)="editInventoryItem(item.id!)" 
                      class="text-primary-600 hover:text-primary-700 transition-colors duration-200">
                Edit
              </button>
              <button (click)="confirmDeleteInventoryItem(item.id!)" 
                      class="text-red-600 hover:text-red-700 transition-colors duration-200">
                Remove
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Empty State -->
    <div *ngIf="filteredItems.length === 0" class="text-center py-12">
      <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path>
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900">No inventory items found</h3>
      <p class="mt-1 text-sm text-gray-500">Start tracking your ingredients by adding them to inventory.</p>
      <div class="mt-6">
        <button routerLink="/inventory/new" class="btn-primary">
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
          </svg>
          Add to Inventory
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Confirm Delete Dialog -->
<app-confirm-dialog
  [isOpen]="showConfirmDialog"
  title="Remove from Inventory"
  message="Are you sure you want to remove this item from inventory? This action cannot be undone."
  confirmText="Remove"
  cancelText="Cancel"
  (confirmed)="deleteInventoryItem()"
  (cancelled)="cancelDelete()">
</app-confirm-dialog>
