// recipespire-frontend/src/pages/Recipes/RecipeDetail.jsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Clock, Users, Edit, Trash2 } from 'lucide-react';
import { recipeService } from '../../services/recipeService';
import LoadingSpinner from '../../components/UI/LoadingSpinner';
import ConfirmDialog from '../../components/UI/ConfirmDialog';
import { useToast } from '../../hooks/useToast';

const RecipeDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [recipe, setRecipe] = useState(null);
  const [loading, setLoading] = useState(true);
  const [deleteDialog, setDeleteDialog] = useState(false);
  
  const { showSuccess, showError } = useToast();

  useEffect(() => {
    loadRecipe();
  }, [id]);

  const loadRecipe = async () => {
    try {
      setLoading(true);
      const response = await recipeService.getRecipeById(id);
      setRecipe(response.data);
    } catch (error) {
      console.error('Error loading recipe:', error);
      showError('Error', 'Failed to load recipe');
      navigate('/recipes');
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteRecipe = async () => {
    try {
      await recipeService.deleteRecipe(id);
      showSuccess('Success', 'Recipe deleted successfully');
      navigate('/recipes');
    } catch (error) {
      console.error('Error deleting recipe:', error);
      showError('Error', 'Failed to delete recipe');
    } finally {
      setDeleteDialog(false);
    }
  };

  const getTotalTime = () => {
    return (recipe?.prepTime || 0) + (recipe?.cookTime || 0);
  };

  if (loading) {
    return <LoadingSpinner />;
  }

  if (!recipe) {
    return (
      <div className="text-center py-12">
        <h3 className="mt-2 text-sm font-medium text-gray-900">Recipe not found</h3>
        <Link to="/recipes" className="mt-4 btn-primary">
          Back to Recipes
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between">
        <div className="flex-1">
          <Link
            to="/recipes"
            className="inline-flex items-center text-primary-600 hover:text-primary-700 mb-4 transition-colors duration-200"
          >
            <ArrowLeft className="w-5 h-5 mr-2" />
            Back to Recipes
          </Link>
          
          <h1 className="text-3xl font-bold text-gray-900 mb-2">{recipe.title}</h1>
          {recipe.description && (
            <p className="text-lg text-gray-600">{recipe.description}</p>
          )}
          
          <div className="flex items-center space-x-6 mt-4">
            {recipe.category && (
              <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-primary-100 text-primary-800">
                {recipe.category}
              </span>
            )}
            {recipe.servings && (
              <div className="flex items-center text-gray-600">
                <Users className="w-5 h-5 mr-1" />
                {recipe.servings} servings
              </div>
            )}
            {getTotalTime() > 0 && (
              <div className="flex items-center text-gray-600">
                <Clock className="w-5 h-5 mr-1" />
                {getTotalTime()} min total
              </div>
            )}
          </div>
        </div>
        
        <div className="flex space-x-3 mt-6 sm:mt-0">
          <Link to={`/recipes/${recipe.id}/edit`} className="btn-secondary flex items-center">
            <Edit className="w-4 h-4 mr-2" />
            Edit
          </Link>
          <button
            onClick={() => setDeleteDialog(true)}
            className="btn-danger flex items-center"
          >
            <Trash2 className="w-4 h-4 mr-2" />
            Delete
          </button>
        </div>
      </div>

      {/* Time Information */}
      {(recipe.prepTime || recipe.cookTime) && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {recipe.prepTime && (
            <div className="text-center p-4 bg-gray-50 rounded-lg">
              <div className="text-2xl font-bold text-primary-600">{recipe.prepTime}</div>
              <div className="text-sm text-gray-600">Prep Time (min)</div>
            </div>
          )}
          {recipe.cookTime && (
            <div className="text-center p-4 bg-gray-50 rounded-lg">
              <div className="text-2xl font-bold text-primary-600">{recipe.cookTime}</div>
              <div className="text-sm text-gray-600">Cook Time (min)</div>
            </div>
          )}
          {getTotalTime() > 0 && (
            <div className="text-center p-4 bg-gray-50 rounded-lg">
              <div className="text-2xl font-bold text-primary-600">{getTotalTime()}</div>
              <div className="text-sm text-gray-600">Total Time (min)</div>
            </div>
          )}
        </div>
      )}

      {/* Ingredients */}
      <div className="card">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Ingredients</h2>
        <div className="space-y-3">
          {recipe.ingredients && recipe.ingredients.length > 0 ? (
            recipe.ingredients.map((ingredient, index) => (
              <div
                key={index}
                className="flex items-center justify-between py-3 border-b border-gray-100 last:border-b-0"
              >
                <div className="flex items-center space-x-3">
                  <div className="w-2 h-2 bg-primary-500 rounded-full"></div>
                  <span className="font-medium text-gray-900">
                    {ingredient.ingredient.name}
                  </span>
                  <span className="text-gray-600">
                    {ingredient.quantity} {ingredient.ingredient.unit}
                  </span>
                </div>
                {ingredient.notes && (
                  <span className="text-sm text-gray-500 italic">{ingredient.notes}</span>
                )}
              </div>
            ))
          ) : (
            <p className="text-gray-500">No ingredients listed</p>
          )}
        </div>
      </div>

      {/* Instructions */}
      <div className="card">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Instructions</h2>
        <div className="prose max-w-none">
          <p className="text-gray-700 leading-relaxed whitespace-pre-line">
            {recipe.instructions}
          </p>
        </div>
      </div>

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={deleteDialog}
        onClose={() => setDeleteDialog(false)}
        onConfirm={handleDeleteRecipe}
        title="Delete Recipe"
        message="Are you sure you want to delete this recipe? This action cannot be undone."
        confirmText="Delete"
        cancelText="Cancel"
      />
    </div>
  );
};

export default RecipeDetail;

// recipesphere-frontend/src/app/components/recipe-detail/recipe-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Recipe } from '../../models/recipe.model';
import { RecipeService } from '../../services/recipe.service';

@Component({
  selector: 'app-recipe-detail',
  templateUrl: './recipe-detail.component.html',
  styleUrls: ['./recipe-detail.component.css']
})
export class RecipeDetailComponent implements OnInit {
  recipe?: Recipe;
  loading = false;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private recipeService: RecipeService
  ) {}

  ngOnInit() {
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.loadRecipe(+params['id']);
      }
    });
  }

  loadRecipe(id: number) {
    this.loading = true;
    this.recipeService.getRecipeById(id).subscribe({
      next: (recipe) => {
        this.recipe = recipe;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading recipe:', error);
        this.loading = false;
        this.router.navigate(['/recipes']);
      }
    });
  }

  editRecipe() {
    this.router.navigate(['/recipes', this.recipe!.id, 'edit']);
  }

  deleteRecipe() {
    if (confirm('Are you sure you want to delete this recipe?')) {
      this.recipeService.deleteRecipe(this.recipe!.id!).subscribe({
        next: () => {
          this.router.navigate(['/recipes']);
        },
        error: (error) => console.error('Error deleting recipe:', error)
      });
    }
  }

  goBack() {
    this.router.navigate(['/recipes']);
  }

  getTotalTime(): number {
    return (this.recipe?.prepTime || 0) + (this.recipe?.cookTime || 0);
  }
}
<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <!-- Loading State -->
  <div *ngIf="loading" class="flex justify-center items-center py-12">
    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
  </div>

  <!-- Recipe Content -->
  <div *ngIf="!loading && recipe" class="space-y-8">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between">
      <div class="flex-1">
        <button (click)="goBack()" 
                class="inline-flex items-center text-primary-600 hover:text-primary-700 mb-4 transition-colors duration-200">
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
          </svg>
          Back to Recipes
        </button>
        
        <h1 class="text-3xl font-bold text-gray-900 mb-2">{{recipe.title}}</h1>
        <p *ngIf="recipe.description" class="text-lg text-gray-600">{{recipe.description}}</p>
        
        <div class="flex items-center space-x-6 mt-4">
          <span *ngIf="recipe.category" 
                class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-primary-100 text-primary-800">
            {{recipe.category}}
          </span>
          <div *ngIf="recipe.servings" class="flex items-center text-gray-600">
            <svg class="w-5 h-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
            </svg>
            {{recipe.servings}} servings
          </div>
          <div *ngIf="getTotalTime() > 0" class="flex items-center text-gray-600">
            <svg class="w-5 h-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            {{getTotalTime()}} min total
          </div>
        </div>
      </div>
      
      <div class="flex space-x-3 mt-6 sm:mt-0">
        <button (click)="editRecipe()" class="btn-secondary">
          <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
          </svg>
          Edit
        </button>
        <button (click)="deleteRecipe()" class="btn-danger">
          <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
          </svg>
          Delete
        </button>
      </div>
    </div>

    <!-- Time Information -->
    <div *ngIf="recipe.prepTime || recipe.cookTime" class="grid grid-cols-2 md:grid-cols-4 gap-4">
      <div *ngIf="recipe.prepTime" class="text-center p-4 bg-gray-50 rounded-lg">
        <div class="text-2xl font-bold text-primary-600">{{recipe.prepTime}}</div>
        <div class="text-sm text-gray-600">Prep Time (min)</div>
      </div>
      <div *ngIf="recipe.cookTime" class="text-center p-4 bg-gray-50 rounded-lg">
        <div class="text-2xl font-bold text-primary-600">{{recipe.cookTime}}</div>
        <div class="text-sm text-gray-600">Cook Time (min)</div>
      </div>
      <div *ngIf="getTotalTime() > 0" class="text-center p-4 bg-gray-50 rounded-lg">
        <div class="text-2xl font-bold text-primary-600">{{getTotalTime()}}</div>
        <div class="text-sm text-gray-600">Total Time (min)</div>
      </div>
    </div>

    <!-- Ingredients -->
    <div class="card">
      <h2 class="text-xl font-semibold text-gray-900 mb-4">Ingredients</h2>
      <div class="space-y-3">
        <div *ngFor="let ingredient of recipe.ingredients" 
             class="flex items-center justify-between py-3 border-b border-gray-100 last:border-b-0">
          <div class="flex items-center space-x-3">
            <div class="w-2 h-2 bg-primary-500 rounded-full"></div>
            <span class="font-medium text-gray-900">{{ingredient.ingredient.name}}</span>
            <span class="text-gray-600">{{ingredient.quantity}} {{ingredient.ingredient.unit}}</span>
          </div>
          <span *ngIf="ingredient.notes" class="text-sm text-gray-500 italic">{{ingredient.notes}}</span>
        </div>
      </div>
    </div>

    <!-- Instructions -->
    <div class="card">
      <h2 class="text-xl font-semibold text-gray-900 mb-4">Instructions</h2>
      <div class="prose max-w-none">
        <p class="text-gray-700 leading-relaxed whitespace-pre-line">{{recipe.instructions}}</p>
      </div>
    </div>
  </div>
</div>
