// recipespire-frontend/src/pages/Inventory/InventoryForm.jsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { X } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import { inventoryService } from '../../services/inventoryService';
import { ingredientService } from '../../services/ingredientService';
import LoadingSpinner from '../../components/UI/LoadingSpinner';
import { useToast } from '../../hooks/useToast';

const schema = yup.object({
  ingredientId: yup.string().required('Please select an ingredient'),
  quantity: yup.number().required('Quantity is required').min(0, 'Quantity must be positive'),
  location: yup.string(),
  expirationDate: yup.string(),
  minStockLevel: yup.number().min(0, 'Minimum stock level must be positive').nullable(),
});

const InventoryForm = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEditMode = Boolean(id);
  const [ingredients, setIngredients] = useState([]);
  const [loading, setLoading] = useState(false);
  const [initialLoading, setInitialLoading] = useState(true);
  
  const { showSuccess, showError } = useToast();

  const locations = ['Pantry', 'Fridge', 'Freezer', 'Spice Rack', 'Counter', 'Other'];

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(schema),
    defaultValues: {
      ingredientId: '',
      quantity: '',
      location: '',
      expirationDate: '',
      minStockLevel: null,
    },
  });

  useEffect(() => {
    loadIngredients();
    if (isEditMode) {
      loadInventoryItem();
    } else {
      setInitialLoading(false);
    }
  }, [id, isEditMode]);

  const loadIngredients = async () => {
    try {
      const response = await ingredientService.getAllIngredients();
      setIngredients(response.data);
    } catch (error) {
      console.error('Error loading ingredients:', error);
      showError('Error', 'Failed to load ingredients');
    }
  };

  const loadInventoryItem = async () => {
    try {
      setInitialLoading(true);
      // Note: We need to get the item from the list since there's no getById endpoint
      const response = await inventoryService.getAllInventoryItems();
      const item = response.data.find(i => i.id === parseInt(id));
      
      if (item) {
        reset({
          ingredientId: item.ingredient.id.toString(),
          quantity: item.quantity,
          location: item.location || '',
          expirationDate: item.expirationDate ? new Date(item.expirationDate).toISOString().split('T')[0] : '',
          minStockLevel: item.minStockLevel,
        });
      } else {
        showError('Error', 'Inventory item not found');
        navigate('/inventory');
      }
    } catch (error) {
      console.error('Error loading inventory item:', error);
      showError('Error', 'Failed to load inventory item');
      navigate('/inventory');
    } finally {
      setInitialLoading(false);
    }
  };

  const onSubmit = async (data) => {
    try {
      setLoading(true);
      
      const inventoryData = {
        ingredient: { id: parseInt(data.ingredientId) },
        quantity: parseFloat(data.quantity),
        location: data.location || null,
        expirationDate: data.expirationDate ? new Date(data.expirationDate) : null,
        minStockLevel: data.minStockLevel ? parseFloat(data.minStockLevel) : null,
      };

      if (isEditMode) {
        await inventoryService.updateInventoryItem(id, inventoryData);
        showSuccess('Success', 'Inventory item updated successfully');
      } else {
        await inventoryService.addToInventory(inventoryData);
        showSuccess('Success', 'Item added to inventory successfully');
      }
      
      navigate('/inventory');
    } catch (error) {
      console.error('Error saving inventory item:', error);
      showError('Error', 'Failed to save inventory item');
    } finally {
      setLoading(false);
    }
  };

  if (initialLoading) {
    return <LoadingSpinner />;
  }

  return (
    <div className="max-w-2xl mx-auto">
      <div className="card">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold text-gray-900">
            {isEditMode ? 'Edit Inventory Item' : 'Add to Inventory'}
          </h1>
          <Link
            to="/inventory"
            className="text-gray-500 hover:text-gray-700 transition-colors duration-200"
          >
            <X className="w-6 h-6" />
          </Link>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          {/* Ingredient Selection */}
          <div>
            <label className="form-label">Ingredient *</label>
            <select {...register('ingredientId')} className="form-input">
              <option value="">Select an ingredient</option>
              {ingredients.map((ingredient) => (
                <option key={ingredient.id} value={ingredient.id}>
                  {ingredient.name} ({ingredient.unit})
                </option>
              ))}
            </select>
            {errors.ingredientId && (
              <p className="mt-1 text-sm text-red-600">{errors.ingredientId.message}</p>
            )}
          </div>

          {/* Quantity */}
          <div>
            <label className="form-label">Quantity *</label>
            <input
              type="number"
              {...register('quantity')}
              className="form-input"
              placeholder="Enter quantity"
              step="0.1"
              min="0"
            />
            {errors.quantity && (
              <p className="mt-1 text-sm text-red-600">{errors.quantity.message}</p>
            )}
          </div>

          {/* Location */}
          <div>
            <label className="form-label">Storage Location</label>
            <select {...register('location')} className="form-input">
              <option value="">Select location</option>
              {locations.map((location) => (
                <option key={location} value={location}>
                  {location}
                </option>
              ))}
            </select>
          </div>

          {/* Expiration Date */}
          <div>
            <label className="form-label">Expiration Date</label>
            <input
              type="date"
              {...register('expirationDate')}
              className="form-input"
            />
          </div>

          {/* Minimum Stock Level */}
          <div>
            <label className="form-label">Minimum Stock Level</label>
            <input
              type="number"
              {...register('minStockLevel')}
              className="form-input"
              placeholder="Alert when stock falls below this level"
              step="0.1"
              min="0"
            />
            <p className="mt-1 text-sm text-gray-500">
              You'll be notified when stock falls below this level
            </p>
            {errors.minStockLevel && (
              <p className="mt-1 text-sm text-red-600">{errors.minStockLevel.message}</p>
            )}
          </div>

          {/* Form Actions */}
          <div className="flex justify-end space-x-4 pt-6 border-t border-gray-200">
            <Link to="/inventory" className="btn-secondary">
              Cancel
            </Link>
            <button
              type="submit"
              disabled={loading}
              className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
            >
              {loading && (
                <div className="animate-spin -ml-1 mr-2 h-4 w-4 border-2 border-white border-t-transparent rounded-full"></div>
              )}
              {loading ? 'Saving...' : (isEditMode ? 'Update Item' : 'Add to Inventory')}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default InventoryForm;

// recipe-spire/src/app/features/inventory/inventory-form/inventory-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { InventoryService } from '../../../core/services/inventory.service';
import { IngredientService } from '../../../core/services/ingredient.service';
import { InventoryItem } from '../../../shared/models/inventory.model';
import { Ingredient } from '../../../shared/models/ingredient.model';
import { ToastService } from '../../../shared/services/toast.service';

@Component({
  selector: 'app-inventory-form',
  templateUrl: './inventory-form.component.html',
  styleUrls: ['./inventory-form.component.css']
})
export class InventoryFormComponent implements OnInit {
  inventoryForm: FormGroup;
  ingredients: Ingredient[] = [];
  isEditMode = false;
  inventoryId?: number;
  loading = false;
  
  locations = ['Pantry', 'Fridge', 'Freezer', 'Spice Rack', 'Counter', 'Other'];

  constructor(
    private fb: FormBuilder,
    private inventoryService: InventoryService,
    private ingredientService: IngredientService,
    private route: ActivatedRoute,
    private router: Router,
    private toastService: ToastService
  ) {
    this.inventoryForm = this.createForm();
  }

  ngOnInit() {
    this.loadIngredients();
    
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.isEditMode = true;
        this.inventoryId = +params['id'];
        this.loadInventoryItem(this.inventoryId);
      }
    });
  }

  createForm(): FormGroup {
    return this.fb.group({
      ingredientId: ['', Validators.required],
      quantity: [null, [Validators.required, Validators.min(0)]],
      location: [''],
      expirationDate: [''],
      minStockLevel: [null, [Validators.min(0)]]
    });
  }

  loadIngredients() {
    this.ingredientService.getAllIngredients().subscribe({
      next: (ingredients) => {
        this.ingredients = ingredients;
      },
      error: (error) => {
        console.error('Error loading ingredients:', error);
        this.toastService.showError('Error', 'Failed to load ingredients');
      }
    });
  }

  loadInventoryItem(id: number) {
    this.loading = true;
    // Note: We would need to implement getInventoryItemById in the service
    // For now, we'll load all items and find the one we need
    this.inventoryService.getAllInventoryItems().subscribe({
      next: (items) => {
        const item = items.find(i => i.id === id);
        if (item) {
          this.populateForm(item);
        } else {
          this.router.navigate(['/inventory']);
        }
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading inventory item:', error);
        this.toastService.showError('Error', 'Failed to load inventory item');
        this.loading = false;
        this.router.navigate(['/inventory']);
      }
    });
  }

  populateForm(item: InventoryItem) {
    this.inventoryForm.patchValue({
      ingredientId: item.ingredient.id,
      quantity: item.quantity,
      location: item.location,
      expirationDate: item.expirationDate ? new Date(item.expirationDate).toISOString().split('T')[0] : '',
      minStockLevel: item.minStockLevel
    });
  }

  onSubmit() {
    if (this.inventoryForm.valid) {
      this.loading = true;
      const formValue = this.inventoryForm.value;
      
      const inventoryItem: any = {
        ingredient: { id: formValue.ingredientId },
        quantity: formValue.quantity,
        location: formValue.location,
        expirationDate: formValue.expirationDate ? new Date(formValue.expirationDate) : null,
        minStockLevel: formValue.minStockLevel
      };

      const operation = this.isEditMode 
        ? this.inventoryService.updateInventoryItem(this.inventoryId!, inventoryItem)
        : this.inventoryService.addToInventory(inventoryItem);

      operation.subscribe({
        next: () => {
          const message = this.isEditMode ? 'Inventory item updated successfully' : 'Item added to inventory successfully';
          this.toastService.showSuccess('Success', message);
          this.router.navigate(['/inventory']);
        },
        error: (error) => {
          console.error('Error saving inventory item:', error);
          this.toastService.showError('Error', 'Failed to save inventory item');
          this.loading = false;
        }
      });
    }
  }

  cancel() {
    this.router.navigate(['/inventory']);
  }
}
<div class="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <div class="card">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold text-gray-900">
        {{isEditMode ? 'Edit Inventory Item' : 'Add to Inventory'}}
      </h1>
      <button (click)="cancel()" 
              class="text-gray-500 hover:text-gray-700 transition-colors duration-200">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>

    <form [formGroup]="inventoryForm" (ngSubmit)="onSubmit()" class="space-y-6">
      <!-- Ingredient Selection -->
      <div>
        <label class="form-label">Ingredient *</label>
        <select formControlName="ingredientId" class="form-input">
          <option value="">Select an ingredient</option>
          <option *ngFor="let ingredient of ingredients" [value]="ingredient.id">
            {{ingredient.name}} ({{ingredient.unit}})
          </option>
        </select>
        <div *ngIf="inventoryForm.get('ingredientId')?.invalid && inventoryForm.get('ingredientId')?.touched" 
             class="mt-1 text-sm text-red-600">
          Please select an ingredient.
        </div>
      </div>

      <!-- Quantity -->
      <div>
        <label class="form-label">Quantity *</label>
        <input type="number" 
               formControlName="quantity"
               class="form-input"
               placeholder="Enter quantity"
               step="0.1"
               min="0">
        <div *ngIf="inventoryForm.get('quantity')?.invalid && inventoryForm.get('quantity')?.touched" 
             class="mt-1 text-sm text-red-600">
          <span *ngIf="inventoryForm.get('quantity')?.errors?.['required']">Quantity is required.</span>
          <span *ngIf="inventoryForm.get('quantity')?.errors?.['min']">Quantity must be greater than 0.</span>
        </div>
      </div>

      <!-- Location -->
      <div>
        <label class="form-label">Storage Location</label>
        <select formControlName="location" class="form-input">
          <option value="">Select location</option>
          <option *ngFor="let location of locations" [value]="location">{{location}}</option>
        </select>
      </div>

      <!-- Expiration Date -->
      <div>
        <label class="form-label">Expiration Date</label>
        <input type="date" 
               formControlName="expirationDate"
               class="form-input">
      </div>

      <!-- Minimum Stock Level -->
      <div>
        <label class="form-label">Minimum Stock Level</label>
        <input type="number" 
               formControlName="minStockLevel"
               class="form-input"
               placeholder="Alert when stock falls below this level"
               step="0.1"
               min="0">
        <p class="mt-1 text-sm text-gray-500">
          You'll be notified when stock falls below this level
        </p>
        <div *ngIf="inventoryForm.get('minStockLevel')?.invalid && inventoryForm.get('minStockLevel')?.touched" 
             class="mt-1 text-sm text-red-600">
          Minimum stock level must be a positive number.
        </div>
      </div>

      <!-- Form Actions -->
      <div class="flex justify-end space-x-4 pt-6 border-t border-gray-200">
        <button type="button" 
                (click)="cancel()"
                class="btn-secondary">
          Cancel
        </button>
        <button type="submit" 
                [disabled]="inventoryForm.invalid || loading"
                class="btn-primary disabled:opacity-50 disabled:cursor-not-allowed">
          <span *ngIf="loading" class="inline-flex items-center">
            <svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Saving...
          </span>
          <span *ngIf="!loading">
            {{isEditMode ? 'Update Item' : 'Add to Inventory'}}
          </span>
        </button>
      </div>
    </form>
  </div>
</div>
