// recipe-spire/src/app/features/recipes/recipe-list/recipe-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Recipe } from '../../../shared/models/recipe.model';
import { RecipeService } from '../../../core/services/recipe.service';
import { ToastService } from '../../../shared/services/toast.service';

@Component({
  selector: 'app-recipe-list',
  templateUrl: './recipe-list.component.html',
  styleUrls: ['./recipe-list.component.css']
})
export class RecipeListComponent implements OnInit {
  recipes: Recipe[] = [];
  filteredRecipes: Recipe[] = [];
  searchQuery = '';
  selectedCategory = '';
  categories = ['Breakfast', 'Lunch', 'Dinner', 'Dessert', 'Snack', 'Appetizer'];
  loading = false;
  showConfirmDialog = false;
  recipeToDelete?: number;

  constructor(
    private recipeService: RecipeService,
    private router: Router,
    private toastService: ToastService
  ) {}

  ngOnInit() {
    this.loadRecipes();
  }

  loadRecipes() {
    this.loading = true;
    this.recipeService.getAllRecipes().subscribe({
      next: (recipes) => {
        this.recipes = recipes;
        this.filteredRecipes = recipes;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading recipes:', error);
        this.toastService.showError('Error', 'Failed to load recipes');
        this.loading = false;
      }
    });
  }

  onSearch() {
    this.filterRecipes();
  }

  onCategoryFilter() {
    this.filterRecipes();
  }

  filterRecipes() {
    let filtered = this.recipes;

    if (this.searchQuery.trim()) {
      filtered = filtered.filter(recipe =>
        recipe.title.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
        (recipe.description && recipe.description.toLowerCase().includes(this.searchQuery.toLowerCase()))
      );
    }

    if (this.selectedCategory) {
      filtered = filtered.filter(recipe => recipe.category === this.selectedCategory);
    }

    this.filteredRecipes = filtered;
  }

  viewRecipe(id: number) {
    this.router.navigate(['/recipes', id]);
  }

  editRecipe(id: number) {
    this.router.navigate(['/recipes', id, 'edit']);
  }

  confirmDeleteRecipe(id: number) {
    this.recipeToDelete = id;
    this.showConfirmDialog = true;
  }

  deleteRecipe() {
    if (this.recipeToDelete) {
      this.recipeService.deleteRecipe(this.recipeToDelete).subscribe({
        next: () => {
          this.toastService.showSuccess('Success', 'Recipe deleted successfully');
          this.loadRecipes();
          this.showConfirmDialog = false;
          this.recipeToDelete = undefined;
        },
        error: (error) => {
          console.error('Error deleting recipe:', error);
          this.toastService.showError('Error', 'Failed to delete recipe');
          this.showConfirmDialog = false;
        }
      });
    }
  }

  cancelDelete() {
    this.showConfirmDialog = false;
    this.recipeToDelete = undefined;
  }

  getTotalTime(recipe: Recipe): number {
    return (recipe.prepTime || 0) + (recipe.cookTime || 0);
  }
}
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <!-- Header -->
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8">
    <div>
      <h1 class="text-3xl font-bold text-gray-900">Recipes</h1>
      <p class="mt-2 text-gray-600">Discover and manage your favorite recipes</p>
    </div>
    <button routerLink="/recipes/new" 
            class="mt-4 sm:mt-0 btn-primary inline-flex items-center">
      <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
      </svg>
      Add Recipe
    </button>
  </div>

  <!-- Search and Filter -->
  <div class="card mb-8">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        <label class="form-label">Search Recipes</label>
        <div class="relative">
          <input type="text" 
                 [(ngModel)]="searchQuery"
                 (input)="onSearch()"
                 placeholder="Search by title or description..."
                 class="form-input pl-10">
          <svg class="absolute left-3 top-3 h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
          </svg>
        </div>
      </div>
      <div>
        <label class="form-label">Filter by Category</label>
        <select [(ngModel)]="selectedCategory" 
                (change)="onCategoryFilter()"
                class="form-input">
          <option value="">All Categories</option>
          <option *ngFor="let category of categories" [value]="category">{{category}}</option>
        </select>
      </div>
    </div>
  </div>

  <!-- Loading State -->
  <app-loading-spinner *ngIf="loading"></app-loading-spinner>

  <!-- Recipe Grid -->
  <div *ngIf="!loading" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <div *ngFor="let recipe of filteredRecipes" 
         class="card hover:shadow-lg transition-shadow duration-300 cursor-pointer group">
      <div (click)="viewRecipe(recipe.id!)">
        <div class="flex items-start justify-between mb-4">
          <h3 class="text-xl font-semibold text-gray-900 group-hover:text-primary-600 transition-colors duration-200">
            {{recipe.title}}
          </h3>
          <span *ngIf="recipe.category" 
                class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary-100 text-primary-800">
            {{recipe.category}}
          </span>
        </div>
        
        <p *ngIf="recipe.description" class="text-gray-600 mb-4 line-clamp-2">
          {{recipe.description}}
        </p>
        
        <div class="flex items-center text-sm text-gray-500 mb-4 space-x-4">
          <div *ngIf="recipe.servings" class="flex items-center">
            <svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
            </svg>
            {{recipe.servings}} servings
          </div>
          <div *ngIf="getTotalTime(recipe) > 0" class="flex items-center">
            <svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            {{getTotalTime(recipe)}} min
          </div>
        </div>
      </div>
      
      <div class="flex justify-end space-x-2 pt-4 border-t border-gray-100">
        <button (click)="editRecipe(recipe.id!)" 
                class="text-primary-600 hover:text-primary-700 font-medium text-sm transition-colors duration-200">
          Edit
        </button>
        <button (click)="confirmDeleteRecipe(recipe.id!)" 
                class="text-red-600 hover:text-red-700 font-medium text-sm transition-colors duration-200">
          Delete
        </button>
      </div>
    </div>
  </div>

  <!-- Empty State -->
  <div *ngIf="!loading && filteredRecipes.length === 0" class="text-center py-12">
    <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
    </svg>
    <h3 class="mt-2 text-sm font-medium text-gray-900">No recipes found</h3>
    <p class="mt-1 text-sm text-gray-500">Get started by creating your first recipe.</p>
    <div class="mt-6">
      <button routerLink="/recipes/new" class="btn-primary">
        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
        </svg>
        Add Recipe
      </button>
    </div>
  </div>
</div>

<!-- Confirm Delete Dialog -->
<app-confirm-dialog
  [isOpen]="showConfirmDialog"
  title="Delete Recipe"
  message="Are you sure you want to delete this recipe? This action cannot be undone."
  confirmText="Delete"
  cancelText="Cancel"
  (confirmed)="deleteRecipe()"
  (cancelled)="cancelDelete()">
</app-confirm-dialog>

// recipespire-frontend/src/pages/Recipes/RecipeList.jsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Search, Clock, Users, Edit, Trash2 } from 'lucide-react';
import { recipeService } from '../../services/recipeService';
import LoadingSpinner from '../../components/UI/LoadingSpinner';
import ConfirmDialog from '../../components/UI/ConfirmDialog';
import { useToast } from '../../hooks/useToast';

const RecipeList = () => {
  const [recipes, setRecipes] = useState([]);
  const [filteredRecipes, setFilteredRecipes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('');
  const [deleteDialog, setDeleteDialog] = useState({ isOpen: false, recipeId: null });
  
  const { showSuccess, showError } = useToast();

  const categories = ['Breakfast', 'Lunch', 'Dinner', 'Dessert', 'Snack', 'Appetizer'];

  useEffect(() => {
    loadRecipes();
  }, []);

  useEffect(() => {
    filterRecipes();
  }, [recipes, searchQuery, selectedCategory]);

  const loadRecipes = async () => {
    try {
      setLoading(true);
      const response = await recipeService.getAllRecipes();
      setRecipes(response.data);
    } catch (error) {
      console.error('Error loading recipes:', error);
      showError('Error', 'Failed to load recipes');
    } finally {
      setLoading(false);
    }
  };

  const filterRecipes = () => {
    let filtered = recipes;

    if (searchQuery.trim()) {
      filtered = filtered.filter(recipe =>
        recipe.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (recipe.description && recipe.description.toLowerCase().includes(searchQuery.toLowerCase()))
      );
    }

    if (selectedCategory) {
      filtered = filtered.filter(recipe => recipe.category === selectedCategory);
    }

    setFilteredRecipes(filtered);
  };

  const handleDeleteRecipe = async () => {
    try {
      await recipeService.deleteRecipe(deleteDialog.recipeId);
      showSuccess('Success', 'Recipe deleted successfully');
      loadRecipes();
    } catch (error) {
      console.error('Error deleting recipe:', error);
      showError('Error', 'Failed to delete recipe');
    } finally {
      setDeleteDialog({ isOpen: false, recipeId: null });
    }
  };

  const getTotalTime = (recipe) => {
    return (recipe.prepTime || 0) + (recipe.cookTime || 0);
  };

  if (loading) {
    return <LoadingSpinner />;
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Recipes</h1>
          <p className="mt-2 text-gray-600">Discover and manage your favorite recipes</p>
        </div>
        <Link
          to="/recipes/new"
          className="mt-4 sm:mt-0 btn-primary inline-flex items-center"
        >
          <Plus className="w-5 h-5 mr-2" />
          Add Recipe
        </Link>
      </div>

      {/* Search and Filter */}
      <div className="card">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="form-label">Search Recipes</label>
            <div className="relative">
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search by title or description..."
                className="form-input pl-10"
              />
              <Search className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
            </div>
          </div>
          <div>
            <label className="form-label">Filter by Category</label>
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="form-input"
            >
              <option value="">All Categories</option>
              {categories.map((category) => (
                <option key={category} value={category}>
                  {category}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Recipe Grid */}
      {filteredRecipes.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredRecipes.map((recipe) => (
            <div key={recipe.id} className="card hover:shadow-lg transition-shadow duration-300">
              <Link to={`/recipes/${recipe.id}`} className="block">
                <div className="flex items-start justify-between mb-4">
                  <h3 className="text-xl font-semibold text-gray-900 hover:text-primary-600 transition-colors duration-200">
                    {recipe.title}
                  </h3>
                  {recipe.category && (
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary-100 text-primary-800">
                      {recipe.category}
                    </span>
                  )}
                </div>
                
                {recipe.description && (
                  <p className="text-gray-600 mb-4 line-clamp-2">
                    {recipe.description}
                  </p>
                )}
                
                <div className="flex items-center text-sm text-gray-500 mb-4 space-x-4">
                  {recipe.servings && (
                    <div className="flex items-center">
                      <Users className="w-4 h-4 mr-1" />
                      {recipe.servings} servings
                    </div>
                  )}
                  {getTotalTime(recipe) > 0 && (
                    <div className="flex items-center">
                      <Clock className="w-4 h-4 mr-1" />
                      {getTotalTime(recipe)} min
                    </div>
                  )}
                </div>
              </Link>
              
              <div className="flex justify-end space-x-2 pt-4 border-t border-gray-100">
                <Link
                  to={`/recipes/${recipe.id}/edit`}
                  className="text-primary-600 hover:text-primary-700 font-medium text-sm transition-colors duration-200 flex items-center"
                >
                  <Edit className="w-4 h-4 mr-1" />
                  Edit
                </Link>
                <button
                  onClick={() => setDeleteDialog({ isOpen: true, recipeId: recipe.id })}
                  className="text-red-600 hover:text-red-700 font-medium text-sm transition-colors duration-200 flex items-center"
                >
                  <Trash2 className="w-4 h-4 mr-1" />
                  Delete
                </button>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="text-center py-12">
          <div className="mx-auto h-12 w-12 text-gray-400 mb-4">
            <ChefHat className="h-12 w-12" />
          </div>
          <h3 className="mt-2 text-sm font-medium text-gray-900">No recipes found</h3>
          <p className="mt-1 text-sm text-gray-500">Get started by creating your first recipe.</p>
          <div className="mt-6">
            <Link to="/recipes/new" className="btn-primary">
              <Plus className="w-5 h-5 mr-2" />
              Add Recipe
            </Link>
          </div>
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={deleteDialog.isOpen}
        onClose={() => setDeleteDialog({ isOpen: false, recipeId: null })}
        onConfirm={handleDeleteRecipe}
        title="Delete Recipe"
        message="Are you sure you want to delete this recipe? This action cannot be undone."
        confirmText="Delete"
        cancelText="Cancel"
      />
    </div>
  );
};

export default RecipeList;
